

version: '3.3'
services:
                app:
                  build : .
                  ports:
                    - "8081:8081"
                  depends_on:
                    - db
#                environment:
#                  MYSQL_HOST: mysql
#                  MYSQL_USER: root
#                  MYSQL_PASSWORD: <your-password>
#                  MYSQL_DB: todos

                db:
                  image: mysql:5.7
                  container_name: db
                  restart: always
                  command: "--default-time-zone=+00:00  --max-allowed-packet=1073741824
                  --symbolic-links=0
                  --explicit_defaults_for_timestamp=1
--character-set-server=utf8
--collation-server=utf8_bin

--max_allowed_packet=2048M
--innodb_log_buffer_size=32M
--innodb_log_file_size=2GB

--query-cache-size=8M
--query-cache-type=1
--query_cache_limit=8M

--join-buffer-size=8M
--table-definition-cache=1024

--open-files-limit=4096


--connect_timeout=120000
--net_read_timeout=120000
--net_write_timeout=120000"

                  environment:
                    MYSQL_DATABASE: 'gih'
                    MYSQL_USER: 'root'
                    MYSQL_PASSWORD: 'root'
                    MYSQL_ROOT_PASSWORD: 'root'
                  ports:
                    # <Port exposed> : <MySQL Port running inside container>
                    - '3306:3306'
#                  expose:
#                    # Opens port 3306 on the container
#                    - '3306'
#                    # Where our data will be persisted
                  volumes:
                    - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: